# Generated by Django 3.2.21 on 2023-09-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id_cidade', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Cidades',
                'ordering': ['nome_cidade'],
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('tp_conta', models.CharField(max_length=30)),
                ('id_banco', models.IntegerField()),
                ('banco', models.CharField(max_length=50)),
                ('conta', models.IntegerField()),
                ('agencia', models.IntegerField()),
                ('operacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ufs',
            fields=[
                ('id_uf', models.AutoField(primary_key=True, serialize=False)),
                ('nome_uf', models.CharField(max_length=30)),
                ('sigla_uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('vinculo', models.CharField(max_length=20)),
                ('cpf', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('id_endereco', models.IntegerField()),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.contas')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appzin.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id_ocorrencia', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('realizada', models.CharField(max_length=1)),
                ('ocorrencia', models.TextField()),
                ('id_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id_endereco', models.IntegerField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=8)),
                ('cep', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=80)),
                ('complemento', models.CharField(blank=True, max_length=60, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('id_cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.cidades')),
            ],
        ),
        migrations.AddField(
            model_name='cidades',
            name='id_uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.ufs'),
        ),
        migrations.AlterUniqueTogether(
            name='cidades',
            unique_together={('nome_cidade', 'id_uf')},
        ),
    ]
