# Generated by Django 3.2.21 on 2023-09-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appzin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=8, unique=True)),
                ('matricula', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id_atividade', models.AutoField(primary_key=True, serialize=False)),
                ('atividade', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('data_postagem', models.DateField()),
                ('data_entrega', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id_matricula', models.IntegerField(primary_key=True, serialize=False)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.alunos')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=7)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id_frequencia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presenca', models.BooleanField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.alunos')),
                ('id_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.frequencia')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id_plano_aula', models.AutoField(primary_key=True, serialize=False)),
                ('tema_aula', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('metodo', models.CharField(max_length=50)),
                ('dia', models.DateField()),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(max_length=8, unique=True)),
                ('codigo', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='enderecos',
            name='id_cidade',
        ),
        migrations.RemoveField(
            model_name='ocorrencias',
            name='id_pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='id_conta',
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Cidades',
        ),
        migrations.DeleteModel(
            name='Contas',
        ),
        migrations.DeleteModel(
            name='Enderecos',
        ),
        migrations.DeleteModel(
            name='Ocorrencias',
        ),
        migrations.DeleteModel(
            name='Pessoas',
        ),
        migrations.DeleteModel(
            name='Ufs',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='id_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appzin.professores'),
        ),
        migrations.AddField(
            model_name='disciplinaaluno',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.disciplinas'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.disciplinas'),
        ),
        migrations.AddField(
            model_name='atividades',
            name='id_plano_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.planoaula'),
        ),
        migrations.AddField(
            model_name='atividadealuno',
            name='id_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appzin.atividades'),
        ),
    ]
